### ISSUE TITLE
How to add preloader in login page?

### ISSUE THREAD

**Issue by essivision** [lykmapipo/ngAA#19]
Hi

I want to add preloader (loading) to login pgae. What should I do? Is it a way to add controller in login page?

**Comment by lykmapipo** [comment]
@essivision 

Hello. You may listen to the following events in `$rootScope`

`signinBegin` when this is fired you may show your loading mask
`signinError` when this fired hide loading mask and show the error
`signinSuccess` when this is fired hide loading mask and you may toast your signin message

Hope it helps

**Comment by essivision** [comment]
Is it a way to add controller in login page?
