### ISSUE TITLE
can't override signinTemplateUrl

### ISSUE THREAD

**Issue by qiangbro** [lykmapipo/ngAA#3]
I want to use my own signin template,
in my main module's config function:
    $authProvider.signinTemplateUrl = 'ui/login.html';
but it doesn't work.

I found that the signinState is always registered before the overriding of signinTemplateUrl.
so it always requesting the default signinTemplateUrl when starting the signinState.

The only thing i can do right now is editing ngAA.js to change the default signinTemplateUrl value of ngAAConfig. Do anyone have some better idea?

**Comment by lykmapipo** [comment]
@qiangbro 

Take a look on [example application](https://github.com/lykmapipo/ngAA/tree/master/example) on how to setup a [singin view](https://github.com/lykmapipo/ngAA/blob/master/example/views/signin.html) and [how to configure it on application](https://github.com/lykmapipo/ngAA#signintemplateurl).

Hope it helps.

**Comment by lykmapipo** [comment]
@qiangbro 

Have you manage to resolve your issue?

**Comment by lykmapipo** [comment]
@qiangbro 

Currently there is a bug on this. Am looking for the way to fix it.

Thanks

**Comment by lykmapipo** [comment]
@qiangbro 

Fixed. Check v0.1.4
